fix ci cd final

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -70,41 +70,37 @@ jobs:
 
 
 # ================= DEPLOY VPS =================
-  deploy:
-    name: Deploy ke VPS
-    runs-on: ubuntu-latest
-    needs: build
+ deploy:
+  name: Deploy ke VPS
+  runs-on: ubuntu-latest
+  needs: build
 
-    steps:
-      - name: Deploy via SSH
-        uses: appleboy/ssh-action@v1.0.3
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USER }}
-          key: ${{ secrets.SERVER_SSH_KEY }}
-          port: 8022
+  steps:
+    - name: Deploy via SSH
+      uses: appleboy/ssh-action@v1.0.3
+      with:
+        host: ${{ secrets.SERVER_HOST }}
+        username: ${{ secrets.SERVER_USER }}
+        key: ${{ secrets.SERVER_SSH_KEY }}
+        port: 8022
 
-          script: |
+        script: |
 
-            echo "🚀 mulai deploy"
+          echo "🚀 mulai deploy"
 
-            cd /home/${{ secrets.SERVER_USER }}/RPL2B-kelompok-4
+          cd /home/${{ secrets.SERVER_USER }}/RPL2B-kelompok-4
 
-            echo "📦 pull image terbaru"
-            docker pull ghcr.io/umamkhoirul06/skilloka_backend:latest
+          echo "pull image terbaru"
+          docker pull ghcr.io/umamkhoirul06/skilloka_backend:latest
 
-            echo "🛑 stop container lama"
-            docker compose down
+          echo "restart container"
+          docker compose down
+          docker compose up -d
 
-            echo "▶️ jalankan container baru"
-            docker compose up -d
+          echo "tunggu postgres siap"
+          sleep 20
 
-            echo "⏳ tunggu database ready"
-            sleep 20
+          echo "run migrate"
+          docker compose exec -T app php artisan migrate --force || echo "skip migrate error"
 
-            docker compose ps
-
-            echo "🧱 migrate database"
-            docker compose exec -T app php artisan migrate --force || true
-
-            echo "✅ deploy selesai"
+          echo "deploy selesai"
